### ISSUE TITLE
Practica 3_Inducciòn Matemática

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-lennin-s-team-1as#1]
[Practica 3.pdf](https://github.com/user-attachments/files/17546438/Practica.3.pdf)

**Comment by Victor-noe12** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
